apiVersion: v1
kind: Pod
metadata:
  labels:
          app: demo-voting-app
          name: voting-app-pod
  name: voting-app-pod
spec:
    containers:
          - name: voting-app
            image: kodekloud/examplevotingapp_vote:v1
            ports:
                  - containerPort: 80
