apiVersion: v1
kind: Pod
metadata:
  labels:
          app: demo-voting-app
          name: postgres-pod
  name: postgres-pod
spec:
    containers:
          - name: postgres
            image: postgres
            ports:
                  - containerPort: 5432
            env:
                  - name: POSTGRESS_USER
                    value: "postgres"
                  - name: POSTGRES_PASSWORD
                    value: "postgres"

