apiVersion: v1
kind: Pod
metadata:
  labels:
          app: demo-voting-app
          name: redis-pod
  name: redis-pod
spec:
    containers:
          - name: redis
            image: redis
            ports:
                  - containerPort: 6379

