apiVersion: v1
kind: Pod
metadata:
  labels:
          app: demo-voting-app
          name: worker-app-pod
  name: worker-app-pod
spec:
    containers:
          - name: worker-app
            image: kodekloud/examplevotingapp_worker:v1

