apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
        selector:
               app: web-pod

        ports: 
           - port: 80
             nodePort: 30103

        type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
        selector:
               app: queue-pod

        ports:
                
           - name: http
             port: 8161
             nodePort: 30102

           - name: endpoint
             port: 61616

        type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-position-tracker
spec:
        selector:
               app: pt-pod

        ports:
           - port: 8080

        type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-api-gateway
spec:
        selector:
               app: gateway-pod

        ports:
           - port: 8080
             nodePort: 30101

        type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-mongodb
spec:
  selector:
    app: mongodb
  ports:
    - name: mongoport
      port: 27017
  type: ClusterIP
