apiVersion: apps/v1
kind: Deployment
metadata: 
      name: gitea
      labels:
              app: gitea-app

spec:
        template:
                metadata:
                        name: gitea-pod
                        labels:                              
                              type: gtrepo                              
                spec:
                        containers:
                                - name: gitea
                                  image: gitea/gitea:linux-amd64
                                  ports:
                                    - containerPort: 3000
                                  env:
                                    - name: USER_UID
                                      value: "1000"
                                    - name: USER_GID
                                      value: "1000"
        selector:
                matchLabels:
                        type: gtrepo                       
        replicas: 2

---
apiVersion: v1
kind: Service
metadata:
      name: gitea-service
      labels:
              app: gitea-app

spec:
        selector:                
             type: gtrepo                    
        ports:
                - port: 3000
                  targetPort: 3000
                  nodePort: 30025

        type: NodePort
