apiVersion: v1
kind: PersistentVolume
metadata:
        name: pv-vol

spec: 
    accessModes:
            - ReadWriteOnce
    capacity:
            storage: 1Gi
    claimRef:
     namespace: default
     name: pvc-vol

    hostPath:
            path: /home/vikasab/kubernetes-volume/data


