apiVersion: v1
kind: Pod
metadata:
  labels:
          app: demo-voting-app
          name: voting-app-pod
  name: voting-app-pod
spec:
    containers:
          - name: voting-app
            image: kodekloud/examplevotingapp_vote:v1
            ports:
                  - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
        name: voting-service
        labels:
                name: voting-service
                app: demo-voting-app

spec:
        type: NodePort
        ports:
            - port: 80
              targetPort: 80
              nodePort: 30004
        selector:
                app: demo-voting-app
                name: voting-app-pod
---
apiVersion: v1
kind: Pod
metadata:
  labels:
          app: demo-voting-app
          name: postgres-pod
  name: postgres-pod
spec:
    containers:
          - name: postgres
            image: postgres
            ports:
                  - containerPort: 5432
            env:
                  - name: POSTGRESS_USER
                    value: "postgres"
                  - name: POSTGRES_PASSWORD
                    value: "postgres"
            volumeMounts:
             - mountPath: "/var/lib/postgresql/db-data"
               name: task-pv-storage

    volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: pvc-vol
---
apiVersion: v1
kind: Service
metadata:
        name: db
        labels:
                name: postgres-service
                app: demo-voting-app

spec:
        ports:
            - port: 5432
              targetPort: 5432
        selector:
                app: demo-voting-app
                name: postgres-pod
---

apiVersion: v1
kind: Pod
metadata:
  labels:
          app: demo-voting-app
          name: worker-app-pod
  name: worker-app-pod
spec:
    containers:
          - name: worker-app
            image: kodekloud/examplevotingapp_worker:v1
---

apiVersion: v1
kind: Pod
metadata:
  labels:
          app: demo-voting-app
          name: redis-pod
  name: redis-pod
spec:
    containers:
          - name: redis
            image: redis
            ports:
                  - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
        name: redis
        labels:
                name: redis-service
                app: demo-voting-app

spec:
        ports:
            - port: 6379
              targetPort: 6379
        selector:
                app: demo-voting-app
                name: redis-pod
---

apiVersion: v1
kind: Pod
metadata:
  labels:
          app: demo-voting-app
          name: result-app-pod
  name: result-app-pod
spec:
    containers:
          - name: result-app
            image: kodekloud/examplevotingapp_result:v1
            ports:
                  - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
        name: result-service
        labels:
                name: result-service
                app: demo-voting-app

spec:
        type: NodePort
        ports:
            - port: 80
              targetPort: 80
              nodePort: 30005
        selector:
                app: demo-voting-app
                name: result-app-pod

